using System.Collections.Generic;

namespace PeriodicWords
{
    static class Data
    {
        public static readonly string[] WordList =
        {
            "ACCURATE",
            "AGES",
            "AGREES",
            "ARTS",
            "ASK",
            "ASKS",
            "ATTACK",
            "ATTACKER",
            "ATTACKERS",
            "ATTACKS",
            "ATTENTION",
            "BABIES",
            "BABY",
            "BACK",
            "BACKS",
            "BACKWARDS",
            "BANK",
            "BANKER",
            "BANKERS",
            "BANKS",
            "BAT",
            "BATS",
            "BATTLES",
            "BATTLESHIP",
            "BATTLESHIPS",
            "BEACH",
            "BEACHES",
            "BEAT",
            "BEATER",
            "BEATERS",
            "BEATS",
            "BEDS",
            "BINGE",
            "BINGES",
            "BIRDS",
            "BLACK",
            "BLACKER",
            "BLANK",
            "BLANKS",
            "BLASTS",
            "BLIND",
            "BLINDS",
            "BLINK",
            "BLINKER",
            "BLINKERS",
            "BLINKS",
            "BLUER",
            "BLUES",
            "BONE",
            "BONES",
            "BOOK",
            "BOOKS",
            "BORN",
            "BOUNCE",
            "BOUNCES",
            "BOW",
            "BOWS",
            "BOXES",
            "BOY",
            "BOYS",
            "BROTHER",
            "BROTHERS",
            "BROWN",
            "BUN",
            "BUNK",
            "BUNKBEDS",
            "BUNKER",
            "BUNKERS",
            "BUNS",
            "BURN",
            "BURNER",
            "BURNERS",
            "BURNS",
            "BUY",
            "BUYER",
            "BUYERS",
            "BUYS",
            "CAMP",
            "CAMPER",
            "CAMPERS",
            "CAMPFIRE",
            "CAMPFIRES",
            "CAMPS",
            "CAN",
            "CANCER",
            "CANNER",
            "CANNERIES",
            "CANNERS",
            "CANNERY",
            "CANS",
            "CAR",
            "CARNIVAL",
            "CARNIVALS",
            "CARS",
            "CASE",
            "CASES",
            "CASTLES",
            "CASTS",
            "CAT",
            "CATS",
            "CHAMPION",
            "CHAMPIONS",
            "CHAMPIONSHIP",
            "CHAMPIONSHIPS",
            "CHASER",
            "CHASERS",
            "CHASES",
            "CHORE",
            "CHORES",
            "CLAW",
            "CLAWS",
            "CLICK",
            "CLICKS",
            "CLOCK",
            "CLOCKS",
            "CLOTH",
            "CLOTHES",
            "CLUB",
            "CLUBS",
            "COASTS",
            "COAT",
            "COATS",
            "CONNECTION",
            "CONNECTIONS",
            "CONSERVATIVES",
            "COOK",
            "COOKER",
            "COOKERS",
            "COOKIES",
            "COOKS",
            "COPIER",
            "COPIERS",
            "COPIES",
            "COPY",
            "CORE",
            "CORES",
            "COVER",
            "COVERS",
            "CRAFTS",
            "CREATES",
            "CREATION",
            "CROOK",
            "CROOKS",
            "CUP",
            "CUPS",
            "CUTS",
            "DYNASTIES",
            "ESSENTIAL",
            "ESSENTIALS",
            "FACTION",
            "FACTIONS",
            "FAT",
            "FATS",
            "FESTIVAL",
            "FESTIVALS",
            "FETCH",
            "FINISH",
            "FINISHER",
            "FINISHERS",
            "FINISHES",
            "FIRE",
            "FIRES",
            "FISH",
            "FIXES",
            "FLAW",
            "FLAWS",
            "FLIER",
            "FLIERS",
            "FLUTE",
            "FLUTES",
            "FLY",
            "FORESTS",
            "FOXES",
            "FRACTION",
            "FRACTIONAL",
            "FRACTIONS",
            "FREES",
            "FROG",
            "FROGS",
            "FRONTLINE",
            "FRONTLINES",
            "FRONTS",
            "FROSTS",
            "FRUITS",
            "FUN",
            "FUNNIER",
            "FUNNY",
            "GAS",
            "GASSES",
            "GENERATE",
            "GENERATES",
            "GENERATION",
            "GENERATIONS",
            "HALES",
            "HATER",
            "HATERS",
            "HAUNTS",
            "HEAR",
            "HEARS",
            "HEARTS",
            "HERO",
            "HEROES",
            "HEROINE",
            "HEROINES",
            "HINTS",
            "HIP",
            "HIPS",
            "HOUSE",
            "HOUSES",
            "HOW",
            "HUNTS",
            "HUSKIES",
            "ICECUBE",
            "KIDS",
            "KISS",
            "KISSES",
            "KITE",
            "KITES",
            "KNIFE",
            "KNIFES",
            "LAND",
            "LANDS",
            "LARGER",
            "LICK",
            "LICKS",
            "LIES",
            "LIFTS",
            "LIKES",
            "LINE",
            "LINES",
            "LION",
            "LIONESS",
            "LIONESSES",
            "LIONS",
            "LISTEN",
            "LISTENER",
            "LISTENERS",
            "LISTENS",
            "LIVER",
            "LIVERS",
            "LIVES",
            "MONOPOLIES",
            "MOTION",
            "MOUNTAIN",
            "MOUNTAINS",
            "MOUNTS",
            "MOUSE",
            "MOVIES",
            "NEVER",
            "NEW",
            "NEWS",
            "NEWSPAPER",
            "NEWSPAPERS",
            "NINE",
            "NINTH",
            "NODS",
            "NOON",
            "NOW",
            "NUKES",
            "OFF",
            "OFFICE",
            "OFFICER",
            "OFFICERS",
            "OFFICES",
            "ONE",
            "OPTION",
            "OPTIONAL",
            "OPTIONS",
            "ORANGE",
            "ORANGES",
            "OVER",
            "OVERPOWER",
            "OVERPOWERS",
            "PANIC",
            "PAPER",
            "PAPERS",
            "PARTICLES",
            "PARTS",
            "PAT",
            "PATH",
            "PATHETIC",
            "PATHS",
            "PATS",
            "PERFECTLY",
            "PERIODS",
            "PIGEON",
            "PIGEONS",
            "PLAN",
            "PLANER",
            "PLANERS",
            "PLANS",
            "PLAY",
            "PLAYER",
            "PLAYERS",
            "PLAYS",
            "POINTS",
            "POP",
            "POPES",
            "POPPER",
            "POPPERS",
            "POPS",
            "POPSICLES",
            "POWER",
            "POWERS",
            "PRAY",
            "PRAYER",
            "PRAYERS",
            "PREFER",
            "PREFERS",
            "PRINCE",
            "PRINCES",
            "PRINCESS",
            "PRINCESSES",
            "PROCESS",
            "PROCESSES",
            "PROFESSION",
            "PROFESSIONAL",
            "PROFESSIONALS",
            "PROFESSIONS",
            "PSYCHIC",
            "PSYCHICS",
            "PSYCHO",
            "PSYCHOTIC",
            "PUNCH",
            "PUNCHER",
            "PUNCHERS",
            "PUNCHES",
            "RACE",
            "RACECAR",
            "RACECARS",
            "RACER",
            "RACERS",
            "RACES",
            "RAIN",
            "RAINBOW",
            "RAINBOWS",
            "RAINIER",
            "RAINS",
            "RAINY",
            "RAN",
            "RATS",
            "REACTION",
            "REAL",
            "RECEIVER",
            "RECEIVERS",
            "REIN",
            "REINCARNATE",
            "REINCARNATES",
            "REINCARNATION",
            "REINS",
            "RESEARCH",
            "RESEARCHER",
            "RESEARCHERS",
            "RESTS",
            "RUB",
            "RUBS",
            "RUIN",
            "RUINS",
            "RUN",
            "RUNNER",
            "RUNNERS",
            "RUNS",
            "RUSH",
            "RUSHER",
            "RUSHERS",
            "RUSHES",
            "SALTS",
            "SAT",
            "SATISFACTION",
            "SATS",
            "SCAR",
            "SCARE",
            "SCARER",
            "SCARERS",
            "SCARES",
            "SCARIER",
            "SCARS",
            "SCARY",
            "SEAS",
            "SECRETS",
            "SEES",
            "SERVER",
            "SERVERS",
            "SHIFTS",
            "SHIP",
            "SHIPS",
            "SHOES",
            "SHORE",
            "SHORELINE",
            "SHORELINES",
            "SHORES",
            "SHUTS",
            "SICK",
            "SINK",
            "SINKS",
            "SITS",
            "SKIES",
            "SKY",
            "SPACE",
            "SPACECRAFTS",
            "SPACER",
            "SPACERS",
            "SPACESHIP",
            "SPACESHIPS",
            "SPINE",
            "SPINES",
            "SPOON",
            "SPOONS",
            "STAIR",
            "STAIRCASE",
            "STAIRCASES",
            "STAIRS",
            "STARE",
            "STARES",
            "STATES",
            "STAY",
            "STAYS",
            "STICK",
            "STICKER",
            "STICKERS",
            "STICKIER",
            "STICKS",
            "STICKY",
            "SUN",
            "SUNNY",
            "SUNS",
            "SUPER",
            "SUPERPOSITION",
            "SURF",
            "SURFS",
            "SWIFTLY",
            "TAKES",
            "TASER",
            "TASERS",
            "TAXES",
            "TEASPOON",
            "TEASPOONS",
            "TENTS",
            "TESTS",
            "THIS",
            "THUNDER",
            "THUNDERS",
            "TICK",
            "TICKS",
            "UPPER",
            "VAMPIRE",
            "VAMPIRES",
            "VIBE",
            "VIBES",
            "VICE",
            "VICIOUS",
            "VIRUS",
            "VIRUSES",
            "VISE",
            "VISION",
            "VISIONAL",
            "VISIONS",
            "VOIDS",
            "WALK",
            "WALKER",
            "WALKERS",
            "WALKS",
            "WAR",
            "WARS",
            "WAS",
            "WATCH",
            "WATCHER",
            "WATCHERS",
            "WATCHES",
            "WATER",
            "WHEN",
            "WHENEVER",
            "WHERE",
            "WHEREVER",
            "WHICH",
            "WHITE",
            "WHITEOUTS",
            "WHO",
            "WIND",
            "WINDOW",
            "WINDOWS",
            "WINDY",
            "WIRE",
            "WIRES",
            "WITCH",
            "WITCHES",
            "WITH",
            "WOLVES",
            "WONDER",
            "WONDERS",
            "WOODS",
            "YARDS",
            "YOU"
        };
        public static readonly Dictionary<string, int> Elements = new Dictionary<string, int>
        {
            { "AC", 89 },
            { "AG", 47 },
            { "AL", 13 },
            { "AM", 95 },
            { "AR", 18 },
            { "AS", 33 },
            { "AT", 85 },
            { "AU", 79 },
            { "BA", 56 },
            { "BE", 4 },
            { "BH", 107 },
            { "BI", 83 },
            { "BK", 97 },
            { "BR", 35 },
            { "CA", 20 },
            { "CD", 48 },
            { "CE", 58 },
            { "CF", 98 },
            { "CL", 17 },
            { "CM", 96 },
            { "CN", 112 },
            { "CO", 27 },
            { "CR", 24 },
            { "CS", 55 },
            { "CU", 29 },
            { "DB", 105 },
            { "DS", 110 },
            { "DY", 66 },
            { "ER", 68 },
            { "ES", 99 },
            { "EU", 63 },
            { "FE", 26 },
            { "FL", 114 },
            { "FM", 100 },
            { "FR", 87 },
            { "GA", 31 },
            { "GD", 64 },
            { "GE", 32 },
            { "HE", 2 },
            { "HF", 72 },
            { "HG", 80 },
            { "HO", 67 },
            { "HS", 108 },
            { "IN", 49 },
            { "IR", 77 },
            { "KR", 36 },
            { "LA", 57 },
            { "LI", 3 },
            { "LR", 103 },
            { "LU", 71 },
            { "LV", 116 },
            { "MC", 115 },
            { "MD", 101 },
            { "MG", 12 },
            { "MN", 25 },
            { "MO", 42 },
            { "MT", 109 },
            { "NA", 11 },
            { "NB", 41 },
            { "ND", 60 },
            { "NE", 10 },
            { "NH", 113 },
            { "NI", 28 },
            { "NO", 102 },
            { "NP", 93 },
            { "OG", 118 },
            { "OS", 76 },
            { "PA", 91 },
            { "PB", 82 },
            { "PD", 46 },
            { "PM", 61 },
            { "PO", 84 },
            { "PR", 59 },
            { "PT", 78 },
            { "PU", 94 },
            { "RA", 88 },
            { "RB", 37 },
            { "RE", 75 },
            { "RF", 104 },
            { "RG", 111 },
            { "RH", 45 },
            { "RN", 86 },
            { "RU", 44 },
            { "SB", 51 },
            { "SC", 21 },
            { "SE", 34 },
            { "SG", 106 },
            { "SI", 14 },
            { "SM", 62 },
            { "SN", 50 },
            { "SR", 38 },
            { "TA", 73 },
            { "TB", 65 },
            { "TC", 43 },
            { "TE", 52 },
            { "TH", 90 },
            { "TI", 22 },
            { "TL", 81 },
            { "TM", 69 },
            { "TS", 117 },
            { "XE", 54 },
            { "YB", 70 },
            { "ZN", 30 },
            { "ZR", 40 },
            { "B", 5 },
            { "C", 6 },
            { "F", 9 },
            { "H", 1 },
            { "I", 53 },
            { "K", 19 },
            { "N", 7 },
            { "O", 8 },
            { "P", 15 },
            { "S", 16 },
            { "U", 92 },
            { "V", 23 },
            { "W", 74 },
            { "Y", 39 }
        };
    }
}